import React, { useState } from 'react';
import { MCQResult, User, SystemSettings } from '../types';
import { X, Share2, ChevronLeft, ChevronRight, Download, FileSearch, Grid, CheckCircle, XCircle, Clock, Award } from 'lucide-react';
import html2canvas from 'html2canvas';

interface Props {
  result: MCQResult;
  user: User;
  settings?: SystemSettings;
  onClose: () => void;
  onViewAnalysis?: (cost: number) => void;
  onPublish?: () => void;
}

export const MarksheetCard: React.FC<Props> = ({ result, user, settings, onClose, onViewAnalysis, onPublish }) => {
  const [page, setPage] = useState(1);
  const [isPublished, setIsPublished] = useState(false);
  const [showOMR, setShowOMR] = useState(false);
  const ITEMS_PER_PAGE = 50;

  const percentage = Math.round((result.score / result.totalQuestions) * 100);
  const attempted = (result.correctCount + result.wrongCount);

  const omrData = result.omrData || [];
  const hasOMR = omrData.length > 0;
  const totalPages = Math.ceil(omrData.length / ITEMS_PER_PAGE);
  const currentData = omrData.slice((page - 1) * ITEMS_PER_PAGE, page * ITEMS_PER_PAGE);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.round(seconds % 60);
    return `${mins}m ${secs}s`;
  };

  const generateStudentId = () => {
    const shortName = (settings?.appShortName || 'IIC').toUpperCase();
    const userInitials = user.name.substring(0, 2).toUpperCase();
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    return `${shortName}-${userInitials}-${randomNum}`;
  };

  const handleDownload = async () => {
      const element = document.getElementById('marksheet-content');
      if (!element) return;
      try {
          const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#f8fafc' });
          const link = document.createElement('a');
          link.download = `Marksheet_${user.name}_${new Date().getTime()}.png`;
          link.href = canvas.toDataURL('image/png');
          link.click();
      } catch (e) {
          console.error('Download failed', e);
      }
  };

  const handleShare = async () => {
      const text = `*${settings?.appName || 'IDEAL INSPIRATION CLASSES'} RESULT*\n\nName: ${user.name}\nScore: ${result.score}/${result.totalQuestions}\nAccuracy: ${percentage}%\nCorrect: ${result.correctCount}\nWrong: ${result.wrongCount}\nTime: ${formatTime(result.totalTimeSeconds)}\nDate: ${new Date(result.date).toLocaleDateString()}\n\nDeveloped by Nadim Anwar\nMarksheet generated by ${settings?.appName || 'IIC App'}`;
      if (navigator.share) {
          try { await navigator.share({ title: 'Result', text }); } catch(e) {}
      } else {
          window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
      }
  };

  const renderOMRRow = (qIndex: number, selected: number, correct: number) => {
      const options = [0, 1, 2, 3];
      return (
          <div key={qIndex} className="flex items-center gap-3 mb-2">
              <span className="w-6 text-[10px] font-bold text-slate-500 text-right">{qIndex + 1}</span>
              <div className="flex gap-1.5">
                  {options.map((opt) => {
                      let bgClass = "bg-white border border-slate-300 text-slate-400";

                      const isSelected = selected === opt;
                      const isCorrect = correct === opt;

                      if (isSelected) {
                          if (isCorrect) bgClass = "bg-green-600 border-green-600 text-white shadow-sm";
                          else bgClass = "bg-red-500 border-red-500 text-white shadow-sm";
                      } else if (isCorrect && selected !== -1) {
                          bgClass = "bg-green-600 border-green-600 text-white opacity-80";
                      } else if (isCorrect && selected === -1) {
                          bgClass = "border-green-500 text-green-600 bg-green-50";
                      }

                      return (
                          <div key={opt} className={`w-6 h-6 rounded-full flex items-center justify-center text-[9px] font-bold transition-all ${bgClass}`}>
                              {String.fromCharCode(65 + opt)}
                          </div>
                      );
                  })}
              </div>
          </div>
      );
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-2 sm:p-4 bg-slate-900/95 backdrop-blur-xl animate-in fade-in overflow-y-auto">
        <div className="w-full max-w-md my-auto mx-auto space-y-4">
            <div id="marksheet-content" className="bg-slate-100 rounded-3xl shadow-2xl overflow-hidden relative">

                <div className="bg-[#1e3a5f] text-white px-6 py-6 text-center relative">
                    <div className="absolute top-4 right-4 opacity-30">
                        <Award size={60} strokeWidth={1} />
                    </div>

                    <div className="flex items-center justify-center gap-3 mb-2">
                        {settings?.appLogo && (
                            <div className="w-12 h-12 rounded-xl bg-white/10 p-1.5 flex items-center justify-center">
                                <img src={settings.appLogo} alt="Logo" className="w-full h-full object-contain" />
                            </div>
                        )}
                        <h1 className="text-xl font-black tracking-wide uppercase">
                            {settings?.appName || 'IDEAL INSPIRATION CLASSES'}
                        </h1>
                    </div>
                    <p className="text-[11px] font-medium tracking-[0.2em] uppercase text-slate-300">
                        Official Marksheet
                    </p>
                </div>

                <div className="bg-white px-6 py-5">
                    <div className="flex justify-between items-start">
                        <div>
                            <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-1">Student Name</p>
                            <h2 className="text-2xl font-black text-slate-800 capitalize">{user.name}</h2>
                            <p className="text-xs text-slate-500 mt-1">ID: {generateStudentId()}</p>
                        </div>
                        <div className="text-right">
                            <p className="text-sm font-semibold text-slate-700">{new Date(result.date).toLocaleDateString()}</p>
                            <p className="text-xs text-slate-500">{new Date(result.date).toLocaleTimeString()}</p>
                        </div>
                    </div>
                </div>

                <div className="bg-[#0f2744] mx-4 rounded-2xl p-8 flex flex-col items-center justify-center">
                    <p className="text-[11px] font-bold text-slate-300 uppercase tracking-[0.2em] mb-4">Total Score</p>

                    <div className="relative w-32 h-32">
                        <svg className="w-full h-full transform -rotate-90">
                            <circle
                                cx="64"
                                cy="64"
                                r="56"
                                fill="none"
                                stroke="#1e3a5f"
                                strokeWidth="8"
                            />
                            <circle
                                cx="64"
                                cy="64"
                                r="56"
                                fill="none"
                                stroke="#3b82f6"
                                strokeWidth="8"
                                strokeLinecap="round"
                                strokeDasharray={`${(percentage / 100) * 352} 352`}
                            />
                        </svg>

                        <div className="absolute inset-0 flex flex-col items-center justify-center">
                            <div className="flex items-baseline">
                                <span className="text-4xl font-black text-yellow-400">{result.score}</span>
                                <span className="text-lg font-bold text-slate-400">/{result.totalQuestions}</span>
                            </div>
                        </div>
                    </div>

                    <div className="mt-3 px-4 py-1.5 bg-slate-700/50 rounded-full">
                        <span className="text-sm font-bold text-green-400">{percentage}% Accuracy</span>
                    </div>
                </div>

                <div className="grid grid-cols-2 gap-4 p-4">
                    <div className="bg-green-50 rounded-2xl p-5 flex items-center gap-4">
                        <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                            <CheckCircle className="text-green-500" size={22} />
                        </div>
                        <div>
                            <p className="text-2xl font-black text-green-600">{result.correctCount}</p>
                            <p className="text-[10px] font-bold text-green-500 uppercase tracking-wider">Correct</p>
                        </div>
                    </div>

                    <div className="bg-red-50 rounded-2xl p-5 flex items-center gap-4">
                        <div className="w-10 h-10 bg-red-100 rounded-full flex items-center justify-center">
                            <XCircle className="text-red-500" size={22} />
                        </div>
                        <div>
                            <p className="text-2xl font-black text-red-600">{result.wrongCount}</p>
                            <p className="text-[10px] font-bold text-red-500 uppercase tracking-wider">Wrong</p>
                        </div>
                    </div>
                </div>

                <div className="mx-4 mb-4 bg-slate-50 rounded-2xl p-5 flex items-center gap-4">
                    <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
                        <Clock className="text-blue-500" size={22} />
                    </div>
                    <div>
                        <p className="text-xl font-black text-slate-700">{formatTime(result.totalTimeSeconds)}</p>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Total Time Taken</p>
                    </div>
                </div>

                {showOMR && (
                    <div className="mx-4 mb-4 p-6 bg-white rounded-2xl border border-slate-200 animate-in slide-in-from-top duration-500">
                        <div className="flex justify-between items-center mb-6">
                            <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Answer Sheet</h3>
                            <span className="text-[10px] font-bold text-blue-500 bg-blue-50 px-3 py-1 rounded-full uppercase tracking-widest">Page {page}/{totalPages}</span>
                        </div>

                        <div className="grid grid-cols-2 md:grid-cols-3 gap-x-6 gap-y-2">
                            {currentData.map((data) => renderOMRRow(data.qIndex, data.selected, data.correct))}
                        </div>

                        {hasOMR && totalPages > 1 && (
                            <div className="flex justify-center items-center gap-4 mt-6 pt-4 border-t border-slate-100">
                                <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="p-2 bg-slate-100 rounded-xl disabled:opacity-30"><ChevronLeft size={18}/></button>
                                <span className="text-sm font-bold text-slate-500">{page} / {totalPages}</span>
                                <button onClick={() => setPage(p => Math.min(totalPages, p + 1))} disabled={page === totalPages} className="p-2 bg-slate-100 rounded-xl disabled:opacity-30"><ChevronRight size={18}/></button>
                            </div>
                        )}
                    </div>
                )}

                <div className="bg-white px-6 py-4 text-center border-t border-slate-200">
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">
                        Marksheet Generated by App
                    </p>
                    <p className="text-[9px] font-medium text-slate-300">
                        Developed by Nadim Anwar
                    </p>
                </div>
            </div>

            <div className="flex flex-wrap items-center justify-center gap-3 py-2 animate-in slide-in-from-bottom duration-700">
                <button
                    onClick={onClose}
                    className="flex items-center justify-center gap-2 px-5 py-3 bg-slate-700 text-white rounded-xl font-bold text-sm shadow-lg hover:bg-slate-600 transition-all active:scale-95"
                >
                    <X size={18} />
                    Close
                </button>

                {onViewAnalysis && (
                    <button
                        onClick={() => onViewAnalysis(0)}
                        className="flex items-center justify-center gap-2 px-5 py-3 bg-blue-600 text-white rounded-xl font-bold text-sm shadow-lg hover:bg-blue-700 transition-all active:scale-95"
                    >
                        <FileSearch size={18} />
                        Analysis
                    </button>
                )}

                <button
                    onClick={() => setShowOMR(!showOMR)}
                    className={`flex items-center justify-center gap-2 px-5 py-3 rounded-xl font-bold text-sm shadow-lg transition-all active:scale-95 ${showOMR ? 'bg-slate-800 text-white' : 'bg-white text-slate-600 border border-slate-200'}`}
                >
                    <Grid size={18} />
                    OMR
                </button>

                <button
                    onClick={handleShare}
                    className="flex items-center justify-center gap-2 px-5 py-3 bg-green-500 text-white rounded-xl font-bold text-sm shadow-lg hover:bg-green-600 transition-all active:scale-95"
                >
                    <Share2 size={18} />
                    Share
                </button>

                <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-2 px-5 py-3 bg-slate-900 text-white rounded-xl font-bold text-sm shadow-lg hover:bg-slate-800 transition-all active:scale-95"
                >
                    <Download size={18} />
                    Download
                </button>
            </div>
        </div>
    </div>
  );
};
